const SCRIPT_PROPERTY_KEY_SLIDE_URL = 'SLIDE_URL';
const SCRIPT_PROPERTY_KEY_INDEX_SHEET = 'INDEX_SHEET';
const SCRIPT_PROPERTY_KEY_SAVED_DETAILS = 'SAVED_DETAILS';
const SCRIPTPROPERTIES = PropertiesService.getScriptProperties();
const SPREADSHEET = SpreadsheetApp.getActiveSpreadsheet();
const SPREADSHEET_ID = SPREADSHEET.getId();
